apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: keycloak-secrets
  namespace: keycloak
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: keycloak
    kind: SecretStore
  target:
    name: keycloak-secrets # name of created secret
  data:
  - secretKey: db-user
    remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      metadataPolicy: None
      key: keycloak-config
      property: db-user
  
  - secretKey: db-password
    remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      metadataPolicy: None
      key: keycloak-config
      property: db-password
  
  - secretKey: keycloak-password
    remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      metadataPolicy: None
      key: keycloak-config
      property: keycloak-password