apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: keycloak
  namespace: keycloak
spec:
  provider:
    vault:
      server: "https://vault.thegraveshouse.com"
      path: keycloak
      version: v2
      auth:
        userPass:
          path: userpass
          username: keycloak
          secretRef:
            name: keycloak-vault-user-password
            namespace: keycloak
            key: password
        # kubernetes:
        #   mountPath: kubernetes
        #   role: external-secrets
        #   serviceAccountRef:
        #     name: external-secrets
        #     namespace: external-secrets