apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: oauth2-proxy-kiwix
  namespace: kiwix
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: kiwix
    kind: SecretStore
  target:
    name: kiwix-oauth2-proxy # name of created secret
  data:
  - secretKey: client-id # name of created secret key
    remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      metadataPolicy: None
      key: kiwix-oauth
      property: client_id
  - secretKey: client-secret # name of created secret key
    remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      metadataPolicy: None
      key: kiwix-oauth
      property: client_secret
  - secretKey: cookie-secret # name of created secret key
    remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      metadataPolicy: None
      key: kiwix-oauth
      property: client_secret