apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: auth-headers-metrics-alertmanager
  namespace: metrics
spec:
  headers:
    browserXssFilter: true
    contentTypeNosniff: true
    forceSTSHeader: true
    frameDeny: true
    sslHost: thegraveshouse.com
    sslRedirect: true
    stsIncludeSubdomains: true
    stsPreload: true
    stsSeconds: 315360000