# Fix for metrics scrapability
# https://github.com/siderolabs/talos/discussions/7214#discussioncomment-11709688
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: etcd-client-cert
  namespace: metrics
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: metrics
    kind: SecretStore
  target:
    name: etcd-client-cert # name of created secret
  data:
  - secretKey: etcd-ca.crt # name of created secret key
    remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      metadataPolicy: None
      key: etcd-client-cert # name of kv secret
      property: etcd-ca
  - secretKey: etcd-client.crt # name of created secret key
    remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      metadataPolicy: None
      key: etcd-client-cert # name of kv secret
      property: etcd-client
  - secretKey: etcd-client-key.key # name of created secret key
    remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      metadataPolicy: None
      key: etcd-client-cert # name of kv secret
      property: etcd-client-key