apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-admin-auth
  namespace: metrics
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: metrics
    kind: SecretStore
  target:
    name: grafana-admin-auth # name of created secret
    template:
      type: kubernetes.io/basic-auth
  data:
  - secretKey: username # name of created secret key
    remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      metadataPolicy: None
      key: grafana-admin-auth # name of kv secret
      property: username
  - secretKey: password # name of created secret key
    remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      metadataPolicy: None
      key: grafana-admin-auth # name of kv secret
      property: password