apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: metrics
  namespace: metrics
spec:
  provider:
    vault:
      server: "https://vault.thegraveshouse.com"
      path: metrics
      version: v2
      auth:
        userPass:
          path: userpass
          username: metrics
          secretRef:
            name: metrics-vault-user-password
            namespace: metrics
            key: password
        # kubernetes:
        #   mountPath: kubernetes
        #   role: external-secrets
        #   serviceAccountRef:
        #     name: external-secrets
        #     namespace: external-secrets