apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: traefik
  namespace: traefik
spec:
  provider:
    vault:
      server: "https://vault.thegraveshouse.com"
      path: traefik
      version: v2
      auth:
        userPass:
          path: userpass
          username: traefik
          secretRef:
            name: traefik-vault-user-password
            namespace: traefik
            key: password
        # kubernetes:
        #   mountPath: kubernetes
        #   role: external-secrets
        #   serviceAccountRef:
        #     name: external-secrets
        #     namespace: external-secrets