apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: kiwix
  namespace: kiwix
spec:
  provider:
    vault:
      server: "https://vault.thegraveshouse.com"
      path: kiwix
      version: v2
      auth:
        userPass:
          path: userpass
          username: kiwix
          secretRef:
            name: kiwix-vault-user-password
            namespace: kiwix
            key: password
        # kubernetes:
        #   mountPath: kubernetes
        #   role: external-secrets
        #   serviceAccountRef:
        #     name: external-secrets
        #     namespace: external-secrets