apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflare-api-token
  namespace: cert-manager
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: cert-manager
    kind: SecretStore
  target:
    name: cloudflare-api-token # name of created secret
  data:
  - secretKey: api-token
    remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      metadataPolicy: None
      key: "cloudflare" # name of kv secret
      property: api-token