apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: cloudflare-staging
  namespace: traefik
spec:
  acme:
    email: admin@chloepetta.net
    privateKeySecretRef:
      name: cloudflare-staging-key
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    solvers:
    - dns01:
        cloudflare:
          apiTokenSecretRef:
            key: api-token
            name: cloudflare-api-token-secret
