apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  provider:
    vault:
      server: "https://vault.thegraveshouse.com"
      path: cert-manager
      version: v2
      auth:
        userPass:
          path: userpass
          username: cert-manager
          secretRef:
            name: cert-manager-vault-user-password
            namespace: cert-manager
            key: password
        # kubernetes:
        #   mountPath: kubernetes
        #   role: external-secrets
        #   serviceAccountRef:
        #     name: external-secrets
        #     namespace: external-secrets