apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: oauth2-proxy-longhorn
  namespace: metrics
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: metrics
    kind: SecretStore
  target:
    name: oauth2-proxy-longhorn # name of created secret
  data:
  - secretKey: client-id # name of created secret key
    remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      metadataPolicy: None
      key: longhorn-oauth
      property: client_id
  - secretKey: client-secret # name of created secret key
    remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      metadataPolicy: None
      key: longhorn-oauth
      property: client_secret