apiVersion: longhorn.io/v1beta2
kind: RecurringJob
metadata:
  name: backup-daily
  namespace: longhorn-system
spec:
  name: backup-daily
  concurrency: 1
  cron: "0 0 * * ?"
  groups:
    - level-1
  retain: 7
  task: backup