apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: longhorn-system
  namespace: longhorn-system
spec:
  provider:
    vault:
      server: "https://vault.thegraveshouse.com"
      path: longhorn-system
      version: v2
      auth:
        userPass:
          path: userpass
          username: longhorn-system
          secretRef:
            name: longhorn-system-vault-user-password
            namespace: longhorn-system
            key: password
        # kubernetes:
        #   mountPath: kubernetes
        #   role: external-secrets
        #   serviceAccountRef:
        #     name: external-secrets
        #     namespace: external-secrets