apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mailu-admin
  namespace: mailu
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: mailu
    kind: SecretStore
  target:
    name: mailu-admin # name of created secret
  data:
  - secretKey: password # name of created secret key
    remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      metadataPolicy: None
      key: mailu-admin # name of kv secret
      property: password