apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: mailu
  namespace: mailu
spec:
  provider:
    vault:
      server: "https://vault.thegraveshouse.com"
      path: mailu
      version: v2
      auth:
        userPass:
          path: userpass
          username: mailu
          secretRef:
            name: mailu-vault-user-password
            namespace: mailu
            key: password
        # kubernetes:
        #   mountPath: kubernetes
        #   role: external-secrets
        #   serviceAccountRef:
        #     name: external-secrets
        #     namespace: external-secrets