apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: harbor-db-password
  namespace: harbor
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: harbor
    kind: SecretStore
  target:
    name: harbor-db-password # name of created secret
  data:
  - secretKey: password # name of created secret key
    remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      metadataPolicy: None
      key: harbor-db-password # name of kv secret
      property: password