apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: harbor
  namespace: harbor
spec:
  provider:
    vault:
      server: "https://vault.thegraveshouse.com"
      path: harbor
      version: v2
      auth:
        userPass:
          path: userpass
          username: harbor
          secretRef:
            name: harbor-vault-user-password
            namespace: harbor
            key: password
        # kubernetes:
        #   mountPath: kubernetes
        #   role: external-secrets
        #   serviceAccountRef:
        #     name: external-secrets
        #     namespace: external-secrets