expose:
  type: route
  route:
    annotations:
      gethomepage.dev/enabled: "true"
      gethomepage.dev/name: Container Repository
      gethomepage.dev/description: Harbor
      gethomepage.dev/icon: harbor.png
      gethomepage.dev/group: Admin
      gethomepage.dev/href: https://harbor.thegraveshouse.com
      gethomepage.dev/pod-selector: ""
      gethomepage.dev/siteMonitor: https://harbor.thegraveshouse.com
    parentRefs:
      - group: gateway.networking.k8s.io
        kind: Gateway
        name: traefik-gateway
        namespace: traefik
    hosts:
      - "harbor.thegraveshouse.com"

externalURL: https://harbor.thegraveshouse.com

existingSecretAdminPassword: "harbor-admin-password"
existingSecretAdminPasswordKey: password # (default to HARBOR_ADMIN_PASSWORD)

updateStrategy:
  type: Recreate

persistence:
  enabled: true
  persistentVolumeClaim:
    registry:
      existingClaim: harbor-registry-pvc
    jobservice:
      jobLog:
        existingClaim: harbor-jobservice-pvc
    trivy:
      existingClaim: harbor-trivy-pvc

containerSecurityContext:
  privileged: true
  allowPrivilegeEscalation: true
  runAsUser: 0
  runAsGroup: 0
  runAsNonRoot: false
  capabilities:
    drop: []

metrics:
  enabled: true
  serviceMonitor:
    enabled: false

trace:
  enabled: false

cache:
  enabled: false

# portal:
#   resources:
#     requests:
#       memory: 256Mi
#       cpu: 100m

# core:
# jobservice:
# registry:

trivy:
  enabled: true
  # resources:
  #   requests:
  #     cpu: 200m
  #     memory: 512Mi
  #   limits:
  #     cpu: 1
  #     memory: 1Gi

database:
  type: external
  external:
    host: 192.168.0.243
    port: 5432
    username: "harbor"
    coreDatabase: "harbor"
    existingSecret: harbor-db-password

redis:
  type: external
  external:
    addr: redis-master.redis.svc.cluster.local:6379

# exporter:
# resources:
#  requests:
#    memory: 256Mi
#    cpu: 100m
