apiVersion: longhorn.io/v1beta2
kind: Volume
metadata:
  name: harbor-trivy
  namespace: longhorn-system
spec:
  size: "1073741824"
  numberOfReplicas: 3
  frontend: blockdev
  accessMode: rwo
  dataLocality: disabled
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: harbor-trivy
spec:
  storageClassName: longhorn
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1Gi
  csi:
    driver: driver.longhorn.io
    volumeHandle: harbor-trivy
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: harbor-trivy-pvc
  namespace: harbor
spec:
  volumeName: harbor-trivy
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi