apiVersion: longhorn.io/v1beta2
kind: Volume
metadata:
  labels:
    backup-target: default
    longhornvolume: jellyfin-media-volume-rwo
    recurring-job-group.longhorn.io/default: enabled
    setting.longhorn.io/remove-snapshots-during-filesystem-trim: ignored
    setting.longhorn.io/replica-auto-balance: ignored
    setting.longhorn.io/snapshot-data-integrity: ignored
  name: jellyfin-media-volume-rwo
  namespace: longhorn-system
spec:
  size: "1099511627776"
  numberOfReplicas: 1
  frontend: blockdev
  accessMode: rwo
  dataLocality: disabled
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jellyfin-media
spec:
  storageClassName: longhorn
  persistentVolumeReclaimPolicy: Retain
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1Ti
  csi:
    driver: driver.longhorn.io
    volumeHandle: jellyfin-media-volume-rwo
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-media-pvc
  namespace: jellyfin
spec:
  volumeName: jellyfin-media
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Ti